sudo: false

git:
  depth: 10

language: node_js


addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-precise-3.6' ]
    packages: [ 'clang-3.6', 'gcc-4.8', 'g++-4.8', 'gcc-4.8-multilib', 'g++-4.8-multilib', 'libc6-dev-i386', 'linux-libc-dev:i386' ]

node_js:
  - 0.5

env: 
  - CXXFLAGS=-std=c++0x CC=gcc-4.8 CXX=g++-4.8

matrix:
  include:
    - node_js: 0.12
      env: CXXFLAGS=-std=c++0x CXX=clang++-3.6 CC=clang NPMOPT=--clang=1 QMDEBUG=--debug

install:
  - npm install --build-from-source $NPMOPT $QMDEBUG

script:
  - npm install -g mocha
  - npm install -g mustache
  - ./tools/genExampleTests.sh
  - ./test/nodejs/test.sh

os: linux
notifications:
  email:  
  - blaz.fortuna@ijs.si
  - jan.rupnik@ijs.si
  - viktor@carvic.si
