sudo: false

git:
  depth: 10

language: node_js

addons:
  apt:
    sources: [ 'ubuntu-toolchain-r-test' ]
    packages: [ 'gcc-4.8', 'g++-4.8', 'gcc-4.8-multilib', 'g++-4.8-multilib', 'libc6-dev-i386', 'linux-libc-dev:i386', 'libgtest-dev' ]

node_js:
  - 6
  - 8

env:
  - CXXFLAGS=-std=c++0x CC=gcc-4.8 CXX=g++-4.8

matrix:
  include:
    - node_js: 4
      env: LLVM_VERSION=3.6.0 CXXFLAGS=-std=c++0x CXX=clang++ CC=clang NPMOPT=--clang=1 QMDEBUG=--debug

cache:
  directories:
    - llvm-3.6.0
    - clang

before_install:
  - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
  - mkdir ${DEPS_DIR} && cd ${DEPS_DIR}
  -
    if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
      if [ -z "$(ls -A llvm-$LLVM_VERSION)" ]; then
        wget -O llvm-$LLVM_VERSION.tar.xz http://llvm.org/releases/$LLVM_VERSION/clang+llvm-$LLVM_VERSION-x86_64-linux-gnu-ubuntu-14.04.tar.xz;
        mkdir llvm-$LLVM_VERSION;
        xzcat llvm-$LLVM_VERSION.tar.xz | tar -xvf - --strip 1 -C llvm-$LLVM_VERSION;
      fi;
      llvm-$LLVM_VERSION/bin/llvm-config --version;
      export LLVM_CONFIG="llvm-$LLVM_VERSION/bin/llvm-config";
    fi
  -
    if [[ "${LLVM_VERSION}" != "" ]]; then
      CLANG_URL="http://llvm.org/releases/${LLVM_VERSION}/clang+llvm-${LLVM_VERSION}-x86_64-linux-gnu-ubuntu-14.04.tar.xz";
      mkdir clang && travis_retry wget --quiet -O - ${CLANG_URL} | tar --strip-components=1 -xJ -C clang;
      export PATH="${DEPS_DIR}/clang/bin:${PATH}";
    fi
  - cd ${TRAVIS_BUILD_DIR}
  - npm install -g npm@5.3.0

install:
  - npm install --build-from-source $NPMOPT $QMDEBUG

script:
  - npm install -g mocha
  - npm install -g mustache
  - ./tools/genExampleTests.sh
  - ./test/nodejs/test.sh
  - cd test/cpp; make

os: linux
notifications:
  email:
  - blaz.fortuna@ijs.si
  - jan.rupnik@ijs.si
  - viktor@carvic.si
