git:
  depth: 10

os: linux
dist: trusty

language: node_js

node_js:
  - "10"
  - "11"
  - "12"
  - "13"
  - "14"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7
      - gcc-7-multilib
      - g++-7-multilib
      - libc6-dev-i386
      - linux-libc-dev:i386

env:
  global:
   - secure: "jnpbDDHcg2Llnqr+eRrpGS+Bi+Xzcs3XJM+go9kFjM/oVVaB5etCJ3pNyD6zZNJRR00xub7XMODtNYGnJAh5b9Z73zN5QhoB4+czijUyibpBGzhQ+V4kEmycz+9ByDTmpH9rJKPB+kNlGU4htUrwSpgr/mUkymqfRgkaoZSVkAo="
   - secure: "dBebU6FnEv3z/ht9ImWUgOGR5acvbzqihuQ/l57dJiblWYl3OWGG+1z3bw+doIhTcPp3JmgeznapN/Cv6cPGx1cuoGQrcFQrWearikzz7zms0ZJr9klNjI2BYEo/wT9B7wB4ubsjuZUXvc203QGFIsIC9qx1+ByeFb1cen7IUIE="
  jobs:
   - CXXFLAGS=-std=c++0x CC=gcc-7 CXX=g++-7

before_install:
  # get commit message
  - COMMIT_MESSAGE=$(git show -s --pretty=oneline $TRAVIS_COMMIT | tr -d '\n')
  # figure out if we should publish
  - PUBLISH_BINARY=false
  - TEST_PUBLISH_BINARY=false
  # if we put [publish binary] in the commit message
  - if test "${COMMIT_MESSAGE#*'[publish binary]'}" != "$COMMIT_MESSAGE"; then PUBLISH_BINARY=true; fi;

install:
  - npm install --build-from-source $NPMOPT $QMDEBUG

script:
  - if [ "$CXX" = "g++-7" ] ; then echo gpp ok ; fi
  - echo status pub && echo $PUBLISH_BINARY && echo $TRAVIS_REPO_SLUG && echo $TRAVIS_PULL_REQUEST
  # publishing will work from qminer/qminer only!
  - if [ "$CXX" = "g++-7" ] && [[ $PUBLISH_BINARY == true ]] && [ "$TRAVIS_REPO_SLUG" = "qminer/qminer" ] && [[ $TRAVIS_PULL_REQUEST == false ]]; then echo publishing && ./node_modules/.bin/node-pre-gyp package unpublish publish; fi
  - npm install -g mocha@6.2.3
  - npm install -g mustache
  - echo "module.exports = require('../index');" > ./node_modules/qminer.js
  - ./tools/genExampleTests.sh;
  - npm test;
  - if [ "$CXX" = "g++-7" ] && [[ $PUBLISH_BINARY == true ]] && [ "$TRAVIS_REPO_SLUG" = "qminer/qminer" ] && [[ $TRAVIS_PULL_REQUEST == false ]]; then echo "publishing 32bit" && ./tools/publish32.sh; fi

notifications:
  email:
  - blaz.fortuna@ijs.si
  - jan.rupnik@ijs.si
  - viktor@carvic.si
