image: Visual Studio 2019

environment:
  matrix:
  - nodejs_version: "8"
  - nodejs_version: "10"
  - nodejs_version: "12"
  - nodejs_version: "14"

platform:
  - x64

configuration:
  - release

shallow_clone: true

install:
  # Set paths
  - if "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - if "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  # Check if we're publishing. Only publish commits including [publish binary] at qminer/qminer (ignore pull requests)
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - ECHO commit message %CM%
  - ECHO %APPVEYOR_REPO_NAME%
  - ps: Install-Product node $env:nodejs_version $env:platform

build_script:
  - npm install -g mocha@6.2.3
  - npm install -g mustache
  - npm install --build-from-source --verbose --msvs_version=2019 --%CONFIGURATION%
  - cd tools
  - genExampleTests.bat
  - cd ..
  - npm test

test: off
deploy: off
