environment:
  node_pre_gyp_accessKeyId:
    secure: jxPeHdKaFnYcMFAUkX+/lcUCKEha3yp5pxxMACxx/lM=
  node_pre_gyp_secretAccessKey:
    secure: 7nDsFrQjWQfhXAPESzf6JO+mslguRKGAPyZ5C4x6Sklcuv4E8/3gkGqoahJJKbZo
  matrix:
  - nodejs_version: "4"
  - nodejs_version: "5"
  - nodejs_version: "6"
  - nodejs_version: "7"
  - nodejs_version: "8"

platform:
  - x86
  - x64

configuration:
  - debug
  - release

shallow_clone: true

install:
  # Set paths
  - SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - if "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - if "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  # Check if we're publishing. Only punlish commits including [publish binary] at qminer/qminer (ignore pull requests)
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - ECHO commit message %CM%
  - ECHO %APPVEYOR_REPO_NAME%
  - ps: Install-Product node $env:nodejs_version $env:platform

build_script:
  - npm install -g mustache
  - npm install --build-from-source --verbose --msvs_version=2015 --%CONFIGURATION%
  - cd tools
  - genExampleTests.bat
  - cd ..
  - .\test\nodejs\test.bat
  - node_modules\.bin\node-pre-gyp package
  - if not "%CONFIGURATION%" == "debug" if not "%CM%" == "%CM:[publish binary]=%" if "%APPVEYOR_REPO_NAME%" == "qminer/qminer" if not defined APPVEYOR_PULL_REQUEST_NUMBER  node_modules\.bin\node-pre-gyp unpublish publish

test: off
deploy: off
