environment:
  matrix:
  - nodejs_version: "11"
  - nodejs_version: "9"

platform:
  - x64

configuration:
  - release

shallow_clone: true

install:
  # Set paths
  - SET PATH=C:\Program Files (x86)\MSBuild\14.0\bin\;%PATH%
  - if "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - if "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  # Check if we're publishing. Only punlish commits including [publish binary] at qminer/qminer (ignore pull requests)
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - ECHO commit message %CM%
  - ECHO %APPVEYOR_REPO_NAME%
  - ps: Install-Product node $env:nodejs_version $env:platform

build_script:
  - npm install -g npm@5.3.0
  - npm install -g mustache
  - npm install --build-from-source --verbose --msvs_version=2015 --%CONFIGURATION%
  - cd tools
  - genExampleTests.bat
  - cd ..
  - .\test\nodejs\test.bat


test: off
deploy: off
