environment:
  node_pre_gyp_accessKeyId:
    secure: jxPeHdKaFnYcMFAUkX+/lcUCKEha3yp5pxxMACxx/lM=
  node_pre_gyp_secretAccessKey:
    secure: 7nDsFrQjWQfhXAPESzf6JO+mslguRKGAPyZ5C4x6Sklcuv4E8/3gkGqoahJJKbZo

platform:
  - x64

shallow_clone: true

install:
  # Set paths
  - SET PATH=C:\Program Files (x86)\MSBuild\12.0\bin\;%PATH%
  - if "%PLATFORM%" == "x64" set PATH=C:\Python27-x64;%PATH%
  - if "%PLATFORM%" == "x86" SET PATH=C:\python27;%PATH%
  # Check if we're publishing. Only punlish commits including [publish binary] at qminer/qminer (ignore pull requests)
  - SET CM=%APPVEYOR_REPO_COMMIT_MESSAGE%
  - ECHO commit message %CM%
  - ECHO %APPVEYOR_REPO_NAME%
  # Install nodist so we can use it to install node.js versions later
  - cmd: git clone https://github.com/marcelklehr/nodist.git c:\nodist 2>&1
  - cmd: SET PATH=C:\nodist\bin;%PATH%
  - cmd: SET NODIST_PREFIX=C:\nodist
  - cmd: nodist selfupdate

before_build:
  - cmd: SET ARCH=x64
  - cmd: SET NODIST_X64=1
  - cmd: call nodist 0.12.7

build_script:
  - npm install -g mustache
  - npm install --build-from-source --verbose --msvs_version=2013
  - cd tools
  - genExampleTests.bat
  - cd ..
  - .\test\nodejs\test.bat
  - node_modules\.bin\node-pre-gyp package
  - if not "%CM%" == "%CM:[publish binary]=%" if "%APPVEYOR_REPO_NAME%" == "qminer/qminer" if not defined APPVEYOR_PULL_REQUEST_NUMBER  node_modules\.bin\node-pre-gyp unpublish publish

after_build:
  - cmd: SET ARCH=x86
  - cmd: SET NODIST_X64=0
  - cmd: call nodist 0.12.7
  - npm install --build-from-source --verbose --msvs_version=2013
  - cd tools
  - genExampleTests.bat
  - cd ..
  - .\test\nodejs\test.bat
  - node_modules\.bin\node-pre-gyp package
  - if not "%CM%" == "%CM:[publish binary]=%" if "%APPVEYOR_REPO_NAME%" == "qminer/qminer" if not defined APPVEYOR_PULL_REQUEST_NUMBER  node_modules\.bin\node-pre-gyp unpublish publish


test: off
deploy: off
